AWSTemplateFormatVersion: "2010-09-09"

Description: {{ metadata['description'] }}

Metadata:
  CommitHash: {{ metadata['commit_hash'] }}
  CommitMessage: {{ metadata['commit_message'] }}

Parameters:
  ResourcePrefix:
    Type: String
    Description: A description to identify resources  (e.g. "my-perf-test")
    MinLength: 2

Resources:
  CustomResourceLambdaFunction:
    Type: AWS::Lambda::Function
    Metadata:
      Comment:
        "Fn::Sub":
          "Function for ${ResourcePrefix}"
    DependsOn: [ CustomResourceLambdaFunctionExecutionRole ]
    Properties:
      Code:
        ZipFile:
          "Fn::Sub": |
            import boto3
            import json
            import logging
            import traceback
            import cfnresponse

            logging.basicConfig()
            logger = logging.getLogger(__name__)
            logger.setLevel(logging.INFO)

            def update_resource(event, context):
                return {'CreatedByCustomResource': 'unknown'}

            def delete_resource(event, context):
                return {'CreatedByCustomResource': 'unknown'}

            def create_resource(event, context):
                client = boto3.client('rds')
                def str_to_bool(s):
                    if s == 'True' or s == 'true':
                        return True
                    elif s == 'False' or s == 'false':
                        return False

                if 'DBInstanceIdentifier' in event['ResourceProperties']:
                    identifier = event['ResourceProperties']['DBInstanceIdentifier']
                else:
                    identifier = 'customresourcedb' + event['StackId'].split('/')[-1]

                # Note - security groups still to be handled.

                result = client.create_db_instance(
                    DBInstanceIdentifier=identifier,
                    DBName=event['ResourceProperties']['DBName'],
                    AllocatedStorage=int(event['ResourceProperties']['AllocatedStorage']),
                    DBInstanceClass=event['ResourceProperties']['DBInstanceClass'],
                    Engine=event['ResourceProperties']['Engine'],
                    MasterUsername=event['ResourceProperties']['MasterUsername'],
                    MasterUserPassword=event['ResourceProperties']['MasterUserPassword'],
                    AvailabilityZone=event['ResourceProperties']['AvailabilityZone'],
                    DBSubnetGroupName=event['ResourceProperties']['DBSubnetGroupName'],
                    Port=int(event['ResourceProperties']['Port']),
                    EngineVersion=event['ResourceProperties']['EngineVersion'],
                    MultiAZ=str_to_bool(event['ResourceProperties']['MultiAZ']),
                    AutoMinorVersionUpgrade=str_to_bool(event['ResourceProperties']['AutoMinorVersionUpgrade'])
                )
                logger.info('Result: ' + json.dumps(result))
                return {'CreatedByCustomResource': 'yup'}, result['DBInstance']['DBInstanceIdentifier']

            def handler(event, context):
                logger.info('Event: ' + json.dumps(event))
                logger.info('Context: ' + str(dir(context)))
                operation = event['RequestType']
                physical_id = None
                data = { }
                try:
                    if operation == 'Create':
                        data, physical_id = create_resource(event, context)
                    elif operation == 'Delete':
                        data = delete_resource(event, context)
                    else:
                        data = update_resource(event, context)
                except Exception as e:
                    logger.error('CloudFormation custom resource {0} failed. Exception: {1}'.format(operation, traceback.format_exc()))
                    status = cfnresponse.FAILED
                else:
                    status = cfnresponse.SUCCESS
                    logger.info('CloudFormation custom resource {0} succeeded. Result data {1}'.format(operation, json.dumps(data)))
                cfnresponse.send(event, context, status, data, physical_id)


      Role: { "Fn::GetAtt": [ CustomResourceLambdaFunctionExecutionRole, Arn ] }
      Timeout: "300"  # Seconds.
      Handler: index.handler
      Runtime: python2.7
      MemorySize: "128"  # MB.

  Policy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - { Ref: CustomResourceLambdaFunctionExecutionRole }
      PolicyName: CommonPolicyForLambdaAndDevelopment
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "arn:aws:logs:*:*:*"
          # - Effect: Allow
          #   Action:
          #     - "s3:CreateBucket"
          #     - "s3:ListAllMyBuckets"
          #   Resource: "*"


  CustomResourceLambdaFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [ lambda.amazonaws.com ]
            Action:
              - sts:AssumeRole
          - Effect: Allow
            Principal:
              AWS:
                - "Fn::Join":
                  - ""
                  - - "arn:aws:iam::"
                    - { Ref: "AWS::AccountId" }
                    - ":"
                    - "root"
            Action:
              - sts:AssumeRole
      Path: /
      # Optional:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess

Outputs:
  CustomResourceLambdaFunction:
    Value: { Ref : CustomResourceLambdaFunction }
  CustomResourceLambdaFunctionARN:
    Value: { "Fn::GetAtt": [ CustomResourceLambdaFunction, Arn ] }
    Export:
      Name: CustomResourceArn-DbRestorer
  CustomResourceLambdaFunctionExecutionRole:
    Value: { Ref : CustomResourceLambdaFunctionExecutionRole }
  CustomResourceLambdaFunctionExecutionRoleARN:
    Value: { "Fn::GetAtt": [ CustomResourceLambdaFunctionExecutionRole, Arn ] }
  SigninUrl:
    Value:
      "Fn::Sub": |
        https://signin.aws.amazon.com/switchrole?account=${AWS::AccountId}&roleName=${CustomResourceLambdaFunctionExecutionRole}&displayName=assumed-role
  TestCommand:
    Value:
      "Fn::Sub": |
        aws lambda invoke --function-name ${CustomResourceLambdaFunction} /tmp/${CustomResourceLambdaFunction}-output.txt; cat /tmp/${CustomResourceLambdaFunction}-output.txt
