AWSTemplateFormatVersion: "2010-09-09"

Description: {{ metadata['description'] }}

Metadata:
  CommitHash: {{ metadata['commit_hash'] }}
  CommitMessage: {{ metadata['commit_message'] }}

Parameters:
  BucketName:
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: { Ref: BucketName }

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: { Ref: Bucket }
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "s3:PutObject"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - ""
                -
                  - "arn:aws:s3:::"
                  - { Ref: Bucket }
                  - "/*"
            Principal:
              AWS:
                - "797873946194"  # Load balancer account for Oregon.
                                  # Need to add this for every region with a LB that logs here.
