# Reference: https://blog.jayway.com/2016/08/17/introduction-to-cloudformation-for-api-gateway/
AWSTemplateFormatVersion: "2010-09-09"
Description: {{ metadata["description"] }}

Metadata:
  CommitHash: {{ metadata["commit_hash"] }}
  CommitMessage: {{ metadata["commit_message"] }}

Resources:
  GreetingLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
      Code:
        ZipFile:
          "Fn::Join":
            - "\n"
            - - "import json"
              - "def handler(event, context):"
              - "    print('Event: ' + json.dumps(event))"
              - "    message = 'World'"
              - "    if 'name' in event and len(event['name']):"
              - "        message = event['name']"
              - "    return { 'greeting': 'Hello, ' + message + '!' }"
      Description: A greeting function
      Handler: index.handler
      Role:
        "Fn::GetAtt": [LambdaExecutionRole, Arn]
      Runtime: python2.7

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ["sts:AssumeRole"]
      Policies:
        - PolicyName: LambdaRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
      # ManagedPolicyArns: ["arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"]

  GreetingApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Greeting API
      Description: API used for Greeting requests
      FailOnWarnings: true

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName:
        "Fn::GetAtt": [GreetingLambda, Arn]
      Principal: apigateway.amazonaws.com
      SourceArn:
        "Fn::Join":
          - ""
          - - "arn:aws:execute-api:"
            - { Ref: "AWS::Region" }
            - ":"
            - { Ref: "AWS::AccountId" }
            - ":"
            - { Ref: "GreetingApi" }
            - "/*"

  ApiGatewayCloudWatchLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: [apigateway.amazonaws.com]
          Action: ["sts:AssumeRole"]
      Policies:
      - PolicyName: ApiGatewayLogsPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action: ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:DescribeLogGroups",
              "logs:DescribeLogStreams", "logs:PutLogEvents", "logs:GetLogEvents",
              "logs:FilterLogEvents"]
            Resource: "*"

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        "Fn::GetAtt": [ApiGatewayCloudWatchLogsRole, Arn]

  GreetingApiStage:
    DependsOn: [ApiGatewayAccount]
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: { Ref: "ApiDeployment" }
      MethodSettings:
      - DataTraceEnabled: true
        HttpMethod: "*"
        LoggingLevel: INFO
        ResourcePath: /*
      RestApiId: { Ref: "GreetingApi" }
      StageName: LATEST

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: [GreetingRequest]
    Properties:
      RestApiId: { Ref: "GreetingApi" }
      StageName: DummyStage

  GreetingResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: { Ref: "GreetingApi" }
      ParentId:
        "Fn::GetAtt": [GreetingApi, RootResourceId]
      # PathPart: "{proxy+}"
      PathPart: greeting

  GreetingRequest:
    DependsOn: LambdaPermission
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        # Type: AWS_PROXY
        Type: AWS
        IntegrationHttpMethod: POST
        Uri:
          "Fn::Join":
            - ""
            - - "arn:aws:apigateway:"
              - { Ref: "AWS::Region" }
              - ":lambda:path/2015-03-31/functions/"
              - "Fn::GetAtt": [GreetingLambda, Arn]
              - "/invocations"
        IntegrationResponses:
        - StatusCode: 200
        RequestTemplates:
          "application/json":
            "Fn::Join":
              - ''
              - - '{'
                - '  "name": "$input.params(''name'')"'
                - '}'
      RequestParameters:
        method.request.querystring.name: false
      ResourceId: { Ref: "GreetingResource" }
      RestApiId: { Ref: "GreetingApi" }
      MethodResponses:
      - StatusCode: 200

Outputs:
  RootUrl:
    Description: Root URL of the API gateway
    Value:
      "Fn::Join":
        - ""
        - - "https://"
          - { Ref: "GreetingApi" }
          - .execute-api.
          - { Ref: "AWS::Region" }
          - ".amazonaws.com"

  CurlCommand:
    Description: Curl command for the endpoint
    Value:
      "Fn::Join":
        - ""
        - - "curl "
          - "https://"
          - { Ref: "GreetingApi" }
          - .execute-api.
          - { Ref: "AWS::Region" }
          - ".amazonaws.com"
          - "/LATEST/greeting"
          - "?name=foobar"
