AWSTemplateFormatVersion: "2010-09-09"

Description: {{ metadata['description'] }}

Metadata:
  CommitHash: {{ metadata['commit_hash'] }}
  CommitMessage: {{ metadata['commit_message'] }}

Parameters:
  ResourcePrefix:
    Type: String

  VpcExportIdentifier:
    Type: String

  SubnetAZ0ExportIdentifier:
    Type: String

  SubnetAZ1ExportIdentifier:
    Type: String

  MultiAz:
    Type: String
    Default: "true"

  PubliclyAccessible:
    Type: String
    Default: "false"

  DbName:
    Type: String

  DbEngine:
    Type: String
    Default: postgres

  DbVersion:
    Type: String
    Default: "9.4.5"

  DbPort:
    Type: String
    Default: "5432"

  DbInstanceClass:
    Type: String
    Default: db.t2.medium

  DBIngressSecurityGroupExportIdentifier:
    Type: String
    Default: ""

Conditions:
  NoDbIngressSecurityGroup:
    "Fn::Equals":
      - { Ref: DBIngressSecurityGroupExportIdentifier }
      - ""


Resources:
  Database:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    Properties:
      AllocatedStorage: "10"
      AllowMajorVersionUpgrade: "false"
      AutoMinorVersionUpgrade: "true"
      AvailabilityZone: { "Fn::Select": [ "0", { "Fn::GetAZs": "" } ] }
      DBInstanceClass: { Ref: DbInstanceClass }
      DBName: { Ref: DbName }
      DBSubnetGroupName: { "Ref" : "DatabaseSubnetGroup" }
      Engine: { Ref: DbEngine }
      EngineVersion: { Ref: DbVersion }
      MasterUsername: "foobarbaz"
      MasterUserPassword: "foobarbaz"
      MultiAZ: { Ref: MultiAz }
      Port: { Ref: DbPort }
      PubliclyAccessible: { Ref: PubliclyAccessible }
      StorageType: standard
      DBSecurityGroups:
        - { "Ref": "DatabaseSecurityGroup" }
      Tags:
        - Key: Name
          Value:
            "Fn::Join":
              - "-"
              - - { Ref: ResourcePrefix }
                - "database"


  DatabaseSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      EC2VpcId:
        "Fn::ImportValue": { Ref: VpcExportIdentifier }
      DBSecurityGroupIngress:
        - "Fn::If":
          - NoDbIngressSecurityGroup
          - { Ref: "AWS::NoValue" }
          - EC2SecurityGroupId: { "Fn::ImportValue" : { Ref: DBIngressSecurityGroupExportIdentifier } }
      GroupDescription: Security group for RDS
      Tags:
        - Key: Name
          Value:
            "Fn::Join":
              - "-"
              - - { Ref: ResourcePrefix }
                - "sg"

  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for the RDS instance
      SubnetIds:
        - "Fn::ImportValue": { Ref: SubnetAZ0ExportIdentifier }
        - "Fn::ImportValue": { Ref: SubnetAZ1ExportIdentifier }
      Tags:
        - Key: Name
          Value:
            "Fn::Join":
              - "-"
              - - { Ref: ResourcePrefix }
                - "subnets"


