AWSTemplateFormatVersion: "2010-09-09"

Description: {{ metadata['description'] }}

Metadata:
  CommitHash: {{ metadata['commit_hash'] }}
  CommitMessage: {{ metadata['commit_message'] }}

Parameters:
  ResourcePrefix:
    Type: String
    Description: A description to identify resources  (e.g. "my-perf-test")
    MinLength: 2

Resources:
  CustomResourceLambdaFunction:
    Type: AWS::Lambda::Function
    Metadata:
      Comment:
        "Fn::Sub":
          "Function for ${ResourcePrefix}"
    DependsOn: [ CustomResourceLambdaFunctionExecutionRole ]
    Properties:
      Code:
        ZipFile:
          "Fn::Sub": |
            import boto3
            import json
            import logging
            import traceback
            from botocore.vendored import requests
            from time import sleep

            logging.basicConfig()
            logger = logging.getLogger(__name__)
            logger.setLevel(logging.INFO)

            def send_cfn_response(event,
                                  context,
                                  response_status,
                                  response_data={},
                                  physical_resource_id=None):

                if physical_resource_id is None:
                    physical_resource_id = context.log_stream_name
                response_data = { str(k): str(v) for k,v in response_data.items() }
                reason = ('See the details in CloudWatch Log Stream: %s from Log Group: %s' % (
                    context.log_stream_name, context.log_group_name))
                if (response_status == 'FAILED') and 'result' in response_data:
                    reason = '%s %s' % (response_data['result'], reason)

                body = {
                    'Status': response_status,
                    'Reason': reason,
                    'PhysicalResourceId': physical_resource_id,
                    'StackId': event['StackId'],
                    'RequestId': event['RequestId'],
                    'LogicalResourceId': event['LogicalResourceId'],
                    'Data': response_data
                }
                response_body = json.dumps(body)
                logger.debug('Response body: %s', response_body)
                try:
                    response = requests.put(event['ResponseURL'],
                                            data=response_body)
                    logger.debug('Status code: %s' % response.status_code)
                except Exception as e:
                    logger.error('send(..) failed executing https.request(..): %s' %
                                 e.message)

            class Status(object):
                SUCCESS = 'SUCCESS'
                FAILED = 'FAILED'

            class Type(object):
                CREATE = 'Create'
                DELETE = 'Delete'
                UPDATE = 'Update'

            def update_resource(event, context):
                return {'CreatedByCustomResource': 'false'}

            def delete_resource(event, context):
                client = boto3.client('ec2')
                enis = client.describe_network_interfaces(Filters=[{'Name': 'group-id','Values': [event['ResourceProperties']['GroupId']]}])
                for eni in enis['NetworkInterfaces']:

                    # We only care about ENI's created by Lambda
                    if eni['Description'].startswith('AWS Lambda VPC ENI: '):

                        # Check if the eni is still attached and attempt to detach
                        if 'Attachment' in eni.keys():
                            logger.info('Detaching ENI...')
                            client.detach_network_interface(AttachmentId=eni['Attachment']['AttachmentId'])
                            logger.info(client.describe_network_interfaces(NetworkInterfaceIds=[eni['NetworkInterfaceId']])['NetworkInterfaces'][0].keys())
                            while 'Attachment' in client.describe_network_interfaces(NetworkInterfaceIds=[eni['NetworkInterfaceId']])['NetworkInterfaces'][0].keys():
                                logger.info('eni still attached, waiting 10 seconds...')
                                sleep(10)

                        # Delete the eni
                        logger.info('Deleting ENI %s' % eni['NetworkInterfaceId'])
                        client.delete_network_interface(NetworkInterfaceId=eni['NetworkInterfaceId'])
                return {'CreatedByCustomResource': 'false'}

            def create_resource(event, context):
                return {'CreatedByCustomResource': 'false'}, 'no-op'

            def handler(event, context):
                logger.info('Event: ' + json.dumps(event))
                logger.info('Context: ' + str(dir(context)))
                operation = event['RequestType']
                physical_id = None
                data = { }
                try:
                    if operation == Type.CREATE:
                        data, physical_id = create_resource(event, context)
                    elif operation == Type.DELETE:
                        data = delete_resource(event, context)
                    else:
                        data = update_resource(event, context)
                except Exception as e:
                    logger.error('CloudFormation custom resource {0} failed. Exception: {1}'.format(operation, traceback.format_exc()))
                    status = Status.FAILED
                else:
                    status = Status.SUCCESS
                    logger.info('CloudFormation custom resource {0} succeeded. Result data {1}'.format(operation, json.dumps(data)))
                send_cfn_response(event, context, status, data, physical_id)


      Role: { "Fn::GetAtt": [ CustomResourceLambdaFunctionExecutionRole, Arn ] }
      Timeout: "300"  # Seconds.
      Handler: index.handler
      Runtime: python2.7
      MemorySize: "128"  # MB.

  Policy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - { Ref: CustomResourceLambdaFunctionExecutionRole }
      PolicyName: CommonPolicyForLambdaAndDevelopment
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "arn:aws:logs:*:*:*"
          - Effect: Allow
            Action:
              - "ec2:DescribeSecurityGroups"
              - "ec2:DescribeNetworkInterfaces"
              - "ec2:CreateNetworkInterface"
              - "ec2:DeleteNetworkInterface"
              - "ec2:DetachNetworkInterface"
            Resource: "*"


  CustomResourceLambdaFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [ lambda.amazonaws.com ]
            Action:
              - sts:AssumeRole
          - Effect: Allow
            Principal:
              AWS:
                - "Fn::Join":
                  - ""
                  - - "arn:aws:iam::"
                    - { Ref: "AWS::AccountId" }
                    - ":"
                    - "root"
            Action:
              - sts:AssumeRole
      Path: /
      # # Optional:
      # ManagedPolicyArns:
      #   - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess


Outputs:
  CustomResourceLambdaFunction:
    Value: { Ref : CustomResourceLambdaFunction }
  CustomResourceLambdaFunctionARN:
    Value: { "Fn::GetAtt": [ CustomResourceLambdaFunction, Arn ] }
    Export:
      Name: CustomResourceArn-VpcLambdaCleaner
  CustomResourceLambdaFunctionExecutionRole:
    Value: { Ref : CustomResourceLambdaFunctionExecutionRole }
  CustomResourceLambdaFunctionExecutionRoleARN:
    Value: { "Fn::GetAtt": [ CustomResourceLambdaFunctionExecutionRole, Arn ] }
  SigninUrl:
    Value:
      "Fn::Sub": |
        https://signin.aws.amazon.com/switchrole?account=${AWS::AccountId}&roleName=${CustomResourceLambdaFunctionExecutionRole}&displayName=assumed-role
  TestCommand:
    Value:
      "Fn::Sub": |
        aws lambda invoke --function-name ${CustomResourceLambdaFunction} /tmp/${CustomResourceLambdaFunction}-output.txt; cat /tmp/${CustomResourceLambdaFunction}-output.txt
